// <auto-generated />
using System;
using EtnaGroup.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EtnaGroup.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("EtnaGroup.Api.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ComplexId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Floors")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComplexId");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Etna Residence, Pristina",
                            Amenities = "24/7 Security, Underground Parking, Fitness Center, Rooftop Terrace",
                            Code = "TARA",
                            ComplexId = 1,
                            CreatedAt = new DateTime(2026, 1, 13, 14, 4, 41, 255, DateTimeKind.Utc).AddTicks(3779),
                            Floors = 12,
                            HeroImageUrl = "/buildings/tara-hero.jpg",
                            Name = "Tara",
                            UpdatedAt = new DateTime(2026, 1, 13, 14, 4, 41, 255, DateTimeKind.Utc).AddTicks(4143)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Etna Residence, Pristina",
                            Amenities = "24/7 Security, Underground Parking, Swimming Pool, Garden Area",
                            Code = "TIANI",
                            ComplexId = 1,
                            CreatedAt = new DateTime(2026, 1, 13, 14, 4, 41, 255, DateTimeKind.Utc).AddTicks(4425),
                            Floors = 10,
                            HeroImageUrl = "/buildings/tiani-hero.jpg",
                            Name = "Tiani",
                            UpdatedAt = new DateTime(2026, 1, 13, 14, 4, 41, 255, DateTimeKind.Utc).AddTicks(4427)
                        });
                });

            modelBuilder.Entity("EtnaGroup.Api.Models.Complex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Complexes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Pristina",
                            Country = "Kosovo",
                            CreatedAt = new DateTime(2026, 1, 13, 14, 4, 41, 253, DateTimeKind.Utc).AddTicks(3775),
                            Description = "Premium residential complex offering modern living spaces with world-class amenities",
                            HeroImageUrl = "/buildings/etna-hero.jpg",
                            Name = "Etna Residence",
                            UpdatedAt = new DateTime(2026, 1, 13, 14, 4, 41, 253, DateTimeKind.Utc).AddTicks(4116)
                        });
                });

            modelBuilder.Entity("EtnaGroup.Api.Models.Inquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("Inquiries");
                });

            modelBuilder.Entity("EtnaGroup.Api.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Bathrooms")
                        .HasPrecision(3, 1)
                        .HasColumnType("TEXT");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExteriorSqm")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Facing")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Floor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gallery")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InteriorSqm")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MoveInReady")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Plan2DUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Plan3DUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalSqm")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bathrooms = 2.5m,
                            Bedrooms = 3,
                            BuildingId = 1,
                            CreatedAt = new DateTime(2026, 1, 13, 14, 4, 41, 256, DateTimeKind.Utc).AddTicks(3444),
                            ExteriorSqm = 85.0m,
                            Facing = "South",
                            Floor = 12,
                            Gallery = "[]",
                            InteriorSqm = 180.5m,
                            MoveInReady = true,
                            Plan2DUrl = "/buildings/tara-plan-2d.png",
                            Plan3DUrl = "/buildings/tara-plan-3d.png",
                            Price = 450000m,
                            Status = 0,
                            TotalSqm = 265.5m,
                            Type = 0,
                            UnitNumber = "PH-01",
                            UpdatedAt = new DateTime(2026, 1, 13, 14, 4, 41, 256, DateTimeKind.Utc).AddTicks(3732)
                        },
                        new
                        {
                            Id = 2,
                            Bathrooms = 3.0m,
                            Bedrooms = 4,
                            BuildingId = 1,
                            CreatedAt = new DateTime(2026, 1, 13, 14, 4, 41, 256, DateTimeKind.Utc).AddTicks(4038),
                            ExteriorSqm = 120.0m,
                            Facing = "North",
                            Floor = 12,
                            Gallery = "[]",
                            InteriorSqm = 220.0m,
                            MoveInReady = false,
                            Plan2DUrl = "/buildings/tara-plan-2d.png",
                            Plan3DUrl = "/buildings/tara-plan-3d.png",
                            Price = 580000m,
                            Status = 0,
                            TotalSqm = 340.0m,
                            Type = 0,
                            UnitNumber = "PH-02",
                            UpdatedAt = new DateTime(2026, 1, 13, 14, 4, 41, 256, DateTimeKind.Utc).AddTicks(4040)
                        },
                        new
                        {
                            Id = 3,
                            Bathrooms = 2.0m,
                            Bedrooms = 2,
                            BuildingId = 1,
                            CreatedAt = new DateTime(2026, 1, 13, 14, 4, 41, 256, DateTimeKind.Utc).AddTicks(4055),
                            ExteriorSqm = 15.0m,
                            Facing = "East",
                            Floor = 5,
                            Gallery = "[]",
                            InteriorSqm = 95.0m,
                            MoveInReady = true,
                            Plan2DUrl = "/buildings/tara-plan-2d.png",
                            Plan3DUrl = "/buildings/tara-plan-3d.png",
                            Price = 185000m,
                            Status = 0,
                            TotalSqm = 110.0m,
                            Type = 2,
                            UnitNumber = "A-05",
                            UpdatedAt = new DateTime(2026, 1, 13, 14, 4, 41, 256, DateTimeKind.Utc).AddTicks(4056)
                        },
                        new
                        {
                            Id = 4,
                            Bathrooms = 1.5m,
                            Bedrooms = 2,
                            BuildingId = 2,
                            CreatedAt = new DateTime(2026, 1, 13, 14, 4, 41, 256, DateTimeKind.Utc).AddTicks(4067),
                            ExteriorSqm = 25.0m,
                            Facing = "West",
                            Floor = 8,
                            Gallery = "[]",
                            InteriorSqm = 120.0m,
                            MoveInReady = true,
                            Plan2DUrl = "/buildings/tiani-plan-2d.png",
                            Plan3DUrl = "/buildings/tiani-plan-3d.png",
                            Price = 245000m,
                            Status = 1,
                            TotalSqm = 145.0m,
                            Type = 1,
                            UnitNumber = "L-01",
                            UpdatedAt = new DateTime(2026, 1, 13, 14, 4, 41, 256, DateTimeKind.Utc).AddTicks(4069)
                        },
                        new
                        {
                            Id = 5,
                            Bathrooms = 2.0m,
                            Bedrooms = 3,
                            BuildingId = 2,
                            CreatedAt = new DateTime(2026, 1, 13, 14, 4, 41, 256, DateTimeKind.Utc).AddTicks(4080),
                            ExteriorSqm = 20.0m,
                            Facing = "South",
                            Floor = 4,
                            Gallery = "[]",
                            InteriorSqm = 135.0m,
                            MoveInReady = false,
                            Plan2DUrl = "/buildings/tiani-plan-2d.png",
                            Plan3DUrl = "/buildings/tiani-plan-3d.png",
                            Price = 265000m,
                            Status = 2,
                            TotalSqm = 155.0m,
                            Type = 3,
                            UnitNumber = "B-03",
                            UpdatedAt = new DateTime(2026, 1, 13, 14, 4, 41, 256, DateTimeKind.Utc).AddTicks(4082)
                        });
                });

            modelBuilder.Entity("EtnaGroup.Api.Models.Building", b =>
                {
                    b.HasOne("EtnaGroup.Api.Models.Complex", "Complex")
                        .WithMany("Buildings")
                        .HasForeignKey("ComplexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complex");
                });

            modelBuilder.Entity("EtnaGroup.Api.Models.Inquiry", b =>
                {
                    b.HasOne("EtnaGroup.Api.Models.Unit", "Unit")
                        .WithMany("Inquiries")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("EtnaGroup.Api.Models.Unit", b =>
                {
                    b.HasOne("EtnaGroup.Api.Models.Building", "Building")
                        .WithMany("Units")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("EtnaGroup.Api.Models.Building", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("EtnaGroup.Api.Models.Complex", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("EtnaGroup.Api.Models.Unit", b =>
                {
                    b.Navigation("Inquiries");
                });
#pragma warning restore 612, 618
        }
    }
}
