// AUTO-GENERATED by scripts/extract-apartment-specs.mjs — do not edit by hand.
// Re-run the script after adding/replacing apartment PDFs.

export interface ApartmentRoom {
  name: string
  area: number
  floor?: string
}

export interface ApartmentSpec {
  type?: string
  totalArea?: number
  greenTerrace?: number
  rooms: ApartmentRoom[]
}

export const apartmentSpecs: Record<string, ApartmentSpec> = {
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku A/Elsa-A-108.4m².pdf": {
    "rooms": [
      {
        "name": "Terasë",
        "area": 4.67,
        "floor": "Qeramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 34.49,
        "floor": "Laminat"
      },
      {
        "name": "Koridori",
        "area": 8.69,
        "floor": "Laminat"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.03,
        "floor": "Laminat"
      },
      {
        "name": "Dhomë gjumi",
        "area": 14.45,
        "floor": "Laminat"
      },
      {
        "name": "WC",
        "area": 1.92
      },
      {
        "name": "Banjo",
        "area": 4.48
      },
      {
        "name": "Banjo",
        "area": 11.28,
        "floor": "Laminat"
      }
    ],
    "type": "3+1",
    "totalArea": 108.4
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku A/Elsa-A-114m².pdf": {
    "rooms": [
      {
        "name": "Koridori",
        "area": 12.74,
        "floor": "Laminat"
      },
      {
        "name": "Dhomë gjumi",
        "area": 14.2,
        "floor": "Laminat"
      },
      {
        "name": "WC",
        "area": 3.34,
        "floor": "Qeramike"
      },
      {
        "name": "Banjo",
        "area": 4.33,
        "floor": "Qeramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.3,
        "floor": "Laminat"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.06,
        "floor": "Laminat"
      },
      {
        "name": "Depo",
        "area": 2.81
      },
      {
        "name": "Qëndrimi ditor",
        "area": 34.25,
        "floor": "Laminat"
      }
    ],
    "totalArea": 114.52,
    "type": "3+1"
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku A/Elsa-A-66.39m².pdf": {
    "rooms": [
      {
        "name": "Koridori",
        "area": 4.88,
        "floor": "Laminat"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 28.04,
        "floor": "Laminat"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.27,
        "floor": "Laminat"
      },
      {
        "name": "Banjo",
        "area": 4.04,
        "floor": "Qeramike"
      },
      {
        "name": "Terasë",
        "area": 8.01
      }
    ],
    "type": "1+1",
    "totalArea": 66.39
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku A/Elsa-A-74.43m².pdf": {
    "rooms": [
      {
        "name": "Qëndrimi ditor",
        "area": 28.05,
        "floor": "Laminat"
      },
      {
        "name": "Dhomë gjumi",
        "area": 16.28,
        "floor": "Laminat"
      },
      {
        "name": "Banjo",
        "area": 4.93,
        "floor": "Qeramike"
      }
    ],
    "type": "1+1"
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku A/Elsa-A-74.4m².pdf": {
    "rooms": [
      {
        "name": "Banjo",
        "area": 4.04
      },
      {
        "name": "Koridori",
        "area": 12,
        "floor": "Laminat"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 22.5,
        "floor": "Laminat"
      },
      {
        "name": "Terasë",
        "area": 5.62,
        "floor": "Qeramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.13
      },
      {
        "name": "Dhomë gjumi",
        "area": 6.75,
        "floor": "Laminat"
      }
    ],
    "totalArea": 74.4,
    "type": "2+1"
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku A/Elsa-A-82.3m².pdf": {
    "rooms": [
      {
        "name": "Banjo",
        "area": 4.37
      },
      {
        "name": "Qëndrimi ditor",
        "area": 28.92
      },
      {
        "name": "Dhomë gjumi",
        "area": 8.82,
        "floor": "Laminat"
      },
      {
        "name": "WC",
        "area": 2.83,
        "floor": "Qeramike"
      },
      {
        "name": "Koridori",
        "area": 8.89,
        "floor": "Laminat"
      },
      {
        "name": "Terasë",
        "area": 3.38
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.07,
        "floor": "Qeramike"
      }
    ],
    "totalArea": 82.3,
    "type": "2+1"
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku A/Elsa-A-93.37m².pdf": {
    "rooms": [
      {
        "name": "Qëndrimi ditor",
        "area": 38.59,
        "floor": "Laminat"
      },
      {
        "name": "Banjo",
        "area": 4.09,
        "floor": "Qeramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.06,
        "floor": "Laminat"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.96,
        "floor": "Laminat"
      },
      {
        "name": "WC",
        "area": 2.38,
        "floor": "Qeramike"
      },
      {
        "name": "Depo",
        "area": 1.98,
        "floor": "Qeramike"
      },
      {
        "name": "Terasë",
        "area": 4.2,
        "floor": "Qeramike"
      }
    ],
    "type": "2+1",
    "totalArea": 93.37
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku B/Elsa-B-113.40m².pdf": {
    "rooms": [
      {
        "name": "Terasë",
        "area": 5.78,
        "floor": "Qeramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 34.24,
        "floor": "Laminat"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.02,
        "floor": "Laminat"
      },
      {
        "name": "Depo",
        "area": 4.47,
        "floor": "Qeramike"
      },
      {
        "name": "Koridori",
        "area": 9.83,
        "floor": "Laminat"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.12,
        "floor": "Laminat"
      },
      {
        "name": "Banjo",
        "area": 4.18,
        "floor": "Qeramike"
      },
      {
        "name": "Banjo",
        "area": 5.69,
        "floor": "Qeramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.15,
        "floor": "Laminat"
      }
    ],
    "totalArea": 113.4,
    "type": "3+1"
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku B/Elsa-B-115.99m².pdf": {
    "rooms": [
      {
        "name": "Terasë",
        "area": 3.2
      },
      {
        "name": "Banjo",
        "area": 4.47,
        "floor": "Qeramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.69,
        "floor": "Laminat"
      },
      {
        "name": "Koridori",
        "area": 9.29,
        "floor": "Laminat"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.11,
        "floor": "Laminat"
      },
      {
        "name": "Banjo",
        "area": 4.06,
        "floor": "Qeramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.16,
        "floor": "Laminat"
      },
      {
        "name": "Depo",
        "area": 1.6,
        "floor": "Qeramike"
      },
      {
        "name": "Terasë",
        "area": 5.78,
        "floor": "Qeramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 37.06,
        "floor": "Laminat"
      }
    ],
    "totalArea": 115.99,
    "type": "3+1"
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku B/Elsa-B-127.11m².pdf": {
    "rooms": [
      {
        "name": "Banjo",
        "area": 4.23,
        "floor": "Qeramike"
      },
      {
        "name": "Banjo",
        "area": 4.42,
        "floor": "Qeramike"
      },
      {
        "name": "Koridori",
        "area": 11.71,
        "floor": "Laminat"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.66,
        "floor": "Laminat"
      },
      {
        "name": "Dhomë gjumi",
        "area": 17.34,
        "floor": "Laminat"
      },
      {
        "name": "Terasë",
        "area": 5.49,
        "floor": "Qeramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 34.13,
        "floor": "Laminat"
      },
      {
        "name": "Dhomë gjumi",
        "area": 17.09,
        "floor": "Laminat"
      },
      {
        "name": "Depo",
        "area": 2.5,
        "floor": "Qeramike"
      }
    ],
    "totalArea": 127.11,
    "type": "3+1"
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku B/Elsa-B-132.21m².pdf": {
    "rooms": [
      {
        "name": "Qëndrimi ditor",
        "area": 18.2,
        "floor": "Laminat"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 15.95,
        "floor": "Laminat"
      },
      {
        "name": "Koridori",
        "area": 18.91,
        "floor": "Laminat"
      },
      {
        "name": "Banjo",
        "area": 3.59,
        "floor": "Qeramike"
      },
      {
        "name": "Depo",
        "area": 1.98
      },
      {
        "name": "Banjo",
        "area": 5.65,
        "floor": "Qeramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 14.15,
        "floor": "Laminat"
      },
      {
        "name": "Dhomë gjumi",
        "area": 14.29,
        "floor": "Laminat"
      },
      {
        "name": "Dhomë gjumi",
        "area": 16.28,
        "floor": "Laminat"
      },
      {
        "name": "Ballkoni",
        "area": 5.41,
        "floor": "Qeramike"
      }
    ],
    "type": "3+1",
    "totalArea": 132.21
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku B/Elsa-B-53.35m².pdf": {
    "rooms": [
      {
        "name": "Qëndrimi ditor",
        "area": 28.04,
        "floor": "Laminat"
      },
      {
        "name": "Banjo",
        "area": 4.91
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.18,
        "floor": "Laminat"
      },
      {
        "name": "Terasë",
        "area": 3.2,
        "floor": "Qeramike"
      }
    ],
    "totalArea": 53.35,
    "type": "1+1"
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku B/Elsa-B-66.26m².pdf": {
    "rooms": [
      {
        "name": "Banjo",
        "area": 4.54,
        "floor": "Qeramike"
      },
      {
        "name": "Koridori",
        "area": 5.93,
        "floor": "Laminat"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.02,
        "floor": "Laminat"
      },
      {
        "name": "Terasë",
        "area": 5.48,
        "floor": "Qeramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 27.96,
        "floor": "Laminat"
      }
    ],
    "totalArea": 66.26,
    "type": "1+1"
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku B/Elsa-B-84.34m².pdf": {
    "rooms": [
      {
        "name": "Terasë",
        "area": 5.2,
        "floor": "Qeramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 29.16,
        "floor": "Laminat"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.31,
        "floor": "Laminat"
      },
      {
        "name": "Banjo",
        "area": 4.11,
        "floor": "Qeramike"
      },
      {
        "name": "Koridori",
        "area": 10.05,
        "floor": "Laminat"
      },
      {
        "name": "Dhomë gjumi",
        "area": 8.72,
        "floor": "Laminat"
      }
    ],
    "totalArea": 84.34,
    "type": "2+1"
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku B/Elsa-B-90.65m².pdf": {
    "rooms": [
      {
        "name": "Qëndrimi ditor",
        "area": 32.23,
        "floor": "Laminat"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.03,
        "floor": "Laminat"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.16,
        "floor": "Laminat"
      },
      {
        "name": "Banjo",
        "area": 5.78,
        "floor": "Qeramike"
      },
      {
        "name": "WC",
        "area": 2.29
      },
      {
        "name": "Ballkoni",
        "area": 5.1,
        "floor": "Qeramike"
      }
    ],
    "type": "2+1"
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku B/Elsa-B-91.11m².pdf": {
    "rooms": [
      {
        "name": "Banjo",
        "area": 4.25,
        "floor": "Qeramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.11,
        "floor": "Laminat"
      },
      {
        "name": "Koridori",
        "area": 9.77,
        "floor": "Laminat"
      },
      {
        "name": "WC",
        "area": 1.92,
        "floor": "Qeramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.02,
        "floor": "Laminat"
      },
      {
        "name": "Terasë",
        "area": 5.2,
        "floor": "Qeramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 33.94,
        "floor": "Laminat"
      }
    ],
    "totalArea": 91.11,
    "type": "2+1"
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku B/Elsa-B-99.65m².pdf": {
    "rooms": [
      {
        "name": "Terasë",
        "area": 5.41
      },
      {
        "name": "Qëndrimi ditor",
        "area": 34.64
      },
      {
        "name": "Depo",
        "area": 2.78
      },
      {
        "name": "Banjo",
        "area": 4.39
      },
      {
        "name": "Dhomë gjumi",
        "area": 15.79,
        "floor": "Laminat"
      },
      {
        "name": "Koridori",
        "area": 6.55,
        "floor": "Laminat"
      },
      {
        "name": "Dhomë gjumi",
        "area": 14.88,
        "floor": "Laminat"
      },
      {
        "name": "WC",
        "area": 2.26,
        "floor": "Qeramike"
      }
    ],
    "totalArea": 99.65,
    "type": "2+1"
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku C/Elsa-C-104.46m².pdf": {
    "rooms": [
      {
        "name": "Qëndrimi ditor",
        "area": 36.53,
        "floor": "Parket"
      },
      {
        "name": "WC",
        "area": 4.19,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Depo",
        "area": 1.98,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 12.85,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 16.34,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 13.78,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.05,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Ballkoni",
        "area": 5.49,
        "floor": "Pllakë Qeramike"
      }
    ],
    "type": "2+1",
    "totalArea": 104.46
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku C/Elsa-C-113.97m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 11.02,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.12,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.15,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.18,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Banjo",
        "area": 5.69,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Depo",
        "area": 4.47,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 9.83,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 5.78,
        "floor": "Pllakë Qeramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 17.68,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 16.56,
        "floor": "Parket"
      }
    ],
    "type": "3+1",
    "totalArea": 113.97
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku C/Elsa-C-115.99m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 13.69,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.11,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.16,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 3.2,
        "floor": "Pllakë Qeramike"
      },
      {
        "name": "Ballkoni",
        "area": 5.78,
        "floor": "Pllakë Qeramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 20.2,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 16.86,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.47,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Banjo",
        "area": 4.06,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 9.29,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 1.6,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "3+1",
    "totalArea": 115.99
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku C/Elsa-C-118.88m².pdf": {
    "rooms": [
      {
        "name": "Qëndrimi ditor",
        "area": 34.18,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 3.42,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Banjo",
        "area": 4.04,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.42,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.72,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.57,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 10.75,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 2.79,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Ballkoni",
        "area": 5.49,
        "floor": "Pllakë Qeramike"
      }
    ],
    "type": "3+1",
    "totalArea": 118.88
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku C/Elsa-C-127.8m².pdf": {
    "rooms": [
      {
        "name": "Qëndrimi ditor",
        "area": 34.7,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 5.65,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Banjo",
        "area": 4.12,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 15.46,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.58,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 17.04,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 1.69,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 4.64,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 5.41,
        "floor": "Pllakë Qeramike"
      }
    ],
    "type": "3+1",
    "totalArea": 127.8
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku C/Elsa-C-128.18m².pdf": {
    "rooms": [
      {
        "name": "Ballkoni",
        "area": 5.49,
        "floor": "Pllakë Qeramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 14.15,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 15.79,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 12.16,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 38,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 2.45,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 13.78,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 5.02,
        "floor": "Pllakë keramike"
      },
      {
        "name": "WC",
        "area": 3.94,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "3+1",
    "totalArea": 128.18
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku C/Elsa-C-53.35m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 13.18,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 14.04,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 14,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.91,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Ballkoni",
        "area": 3.2,
        "floor": "Pllakë Qeramike"
      }
    ],
    "type": "1+1",
    "totalArea": 53.35
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku C/Elsa-C-66.26m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 13.02,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 5.48,
        "floor": "Pllakë Qeramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 16.24,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 11.72,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.54,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 5.49,
        "floor": "Parket"
      }
    ],
    "type": "1+1",
    "totalArea": 66.26
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku C/Elsa-C-67.98m².pdf": {
    "rooms": [
      {
        "name": "Qëndrimi ditor",
        "area": 28.14,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 5.63,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 15.87,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 4.97,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 4.02,
        "floor": "Pllakë Qeramike"
      }
    ],
    "type": "1+1",
    "totalArea": 67.98
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku C/Elsa-C-84.34m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 13.31,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 5.2,
        "floor": "Pllakë Qeramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 16.65,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 12.51,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.11,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 10.05,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 8.72,
        "floor": "Parket"
      },
      {
        "name": "WC",
        "area": 2.13,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "2+1",
    "totalArea": 84.34
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku C/Elsa-C-91.11m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 11.11,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.02,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 5.2,
        "floor": "Pllakë Qeramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 20.2,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 16.86,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.25,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 9.79,
        "floor": "Parket"
      },
      {
        "name": "WC",
        "area": 1.92,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "2+1",
    "totalArea": 91.11
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku C/Elsa-C-99.65m².pdf": {
    "rooms": [
      {
        "name": "Ballkoni",
        "area": 5.41,
        "floor": "Pllakë Qeramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 15.79,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 14.88,
        "floor": "Parket"
      },
      {
        "name": "WC",
        "area": 2.26,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Banjo",
        "area": 4.35,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Depo",
        "area": 2.78,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 6.55,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 14.75,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 19.89,
        "floor": "Parket"
      }
    ],
    "type": "2+1",
    "totalArea": 99.65
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku D/Elsa-D-104.46m².pdf": {
    "rooms": [
      {
        "name": "Qëndrimi ditor",
        "area": 36.53,
        "floor": "Parket"
      },
      {
        "name": "WC",
        "area": 4.19,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Depo",
        "area": 1.98,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 12.85,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 16.34,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 13.78,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.05,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Ballkoni",
        "area": 5.49,
        "floor": "Pllakë Qeramike"
      }
    ],
    "type": "2+1",
    "totalArea": 104.46
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku D/Elsa-D-113.97m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 11.02,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.12,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.15,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.18,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Banjo",
        "area": 5.69,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Depo",
        "area": 4.47,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 9.83,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 5.78,
        "floor": "Pllakë Qeramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 17.68,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 16.56,
        "floor": "Parket"
      }
    ],
    "type": "3+1",
    "totalArea": 113.97
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku D/Elsa-D-115.9m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 13.69,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.11,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.16,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 3.2,
        "floor": "Pllakë Qeramike"
      },
      {
        "name": "Ballkoni",
        "area": 5.78,
        "floor": "Pllakë Qeramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 20.2,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 16.86,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.47,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Banjo",
        "area": 4.06,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 9.29,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 1.6,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "3+1",
    "totalArea": 115.99
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku D/Elsa-D-118.88m².pdf": {
    "rooms": [
      {
        "name": "Qëndrimi ditor",
        "area": 34.18,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 3.42,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Banjo",
        "area": 4.04,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.42,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.72,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.57,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 10.75,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 2.79,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Ballkoni",
        "area": 5.49,
        "floor": "Pllakë Qeramike"
      }
    ],
    "type": "3+1",
    "totalArea": 118.88
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku D/Elsa-D-127.80m².pdf": {
    "rooms": [
      {
        "name": "Qëndrimi ditor",
        "area": 34.7,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 5.65,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Banjo",
        "area": 4.12,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 15.46,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.58,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 17.04,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 1.69,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 4.64,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 5.41,
        "floor": "Pllakë Qeramike"
      }
    ],
    "type": "3+1",
    "totalArea": 127.8
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku D/Elsa-D-128.18m².pdf": {
    "rooms": [
      {
        "name": "Ballkoni",
        "area": 5.49,
        "floor": "Pllakë Qeramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 14.15,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 15.79,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 12.16,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 38,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 2.45,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 13.78,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 5.02,
        "floor": "Pllakë keramike"
      },
      {
        "name": "WC",
        "area": 3.94,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "3+1",
    "totalArea": 128.18
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku D/Elsa-D-53.35m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 13.18,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 14.04,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 14,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.91,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Ballkoni",
        "area": 3.2,
        "floor": "Pllakë Qeramike"
      }
    ],
    "type": "1+1",
    "totalArea": 53.35
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku D/Elsa-D-66.26m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 13.02,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 5.48,
        "floor": "Pllakë Qeramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 16.24,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 11.72,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.54,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 5.49,
        "floor": "Parket"
      }
    ],
    "type": "1+1",
    "totalArea": 66.26
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku D/Elsa-D-67.98m².pdf": {
    "rooms": [
      {
        "name": "Qëndrimi ditor",
        "area": 28.14,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 5.63,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 15.87,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 4.97,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 4.02,
        "floor": "Pllakë Qeramike"
      }
    ],
    "type": "1+1",
    "totalArea": 67.98
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku D/Elsa-D-84.34m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 13.31,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 5.2,
        "floor": "Pllakë Qeramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 16.65,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 12.51,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.11,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 10.05,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 8.72,
        "floor": "Parket"
      },
      {
        "name": "WC",
        "area": 2.13,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "2+1",
    "totalArea": 84.34
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku D/Elsa-D-91.11m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 11.11,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.02,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 5.2,
        "floor": "Pllakë Qeramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 20.2,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 16.86,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.25,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 9.79,
        "floor": "Parket"
      },
      {
        "name": "WC",
        "area": 1.92,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "2+1",
    "totalArea": 91.11
  },
  "Residences Apartments/Elsa Residence PDF/Elsa Blloku D/Elsa-D-99.65m².pdf": {
    "rooms": [
      {
        "name": "Ballkoni",
        "area": 5.41,
        "floor": "Pllakë Qeramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 15.79,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 14.88,
        "floor": "Parket"
      },
      {
        "name": "WC",
        "area": 2.26,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Banjo",
        "area": 4.35,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Depo",
        "area": 2.78,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 6.55,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 14.75,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 19.89,
        "floor": "Parket"
      }
    ],
    "type": "2+1",
    "totalArea": 99.65
  },
  "Residences Apartments/Joni Residence PDF/Kati 1-6/Joni-K1-6-108.5m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 13.1,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 8.5,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 5,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 12.3,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 19.9,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 5.7,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 11.1,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 2.1,
        "floor": "Pllakë keramike"
      },
      {
        "name": "WC",
        "area": 1.7,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 11,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 4.3,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "3+1"
  },
  "Residences Apartments/Joni Residence PDF/Kati 1-6/Joni-K1-6-109.0m².pdf": {
    "rooms": [
      {
        "name": "Ballkoni",
        "area": 6.5,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Ballkoni",
        "area": 4.7,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "3+1"
  },
  "Residences Apartments/Joni Residence PDF/Kati 1-6/Joni-K1-6-52.0m².pdf": {
    "rooms": [
      {
        "name": "Ballkoni",
        "area": 5.2,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "1+1"
  },
  "Residences Apartments/Joni Residence PDF/Kati 1-6/Joni-K1-6-83.6m².pdf": {
    "rooms": [
      {
        "name": "Kuzhina/Tryezaria",
        "area": 10.5,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 17,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 6.9,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 10.6,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.6,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 7.1,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.4,
        "floor": "Pllakë keramike"
      },
      {
        "name": "WC",
        "area": 2.2,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Depo",
        "area": 1.5,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "2+1"
  },
  "Residences Apartments/Joni Residence PDF/Kati 1/Joni-K1-102.8m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 12.6,
        "floor": "Parket"
      },
      {
        "name": "WC",
        "area": 1.7,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "2+1"
  },
  "Residences Apartments/Joni Residence PDF/Kati 1/Joni-K1-112.3m².pdf": {
    "rooms": [],
    "type": "2+1"
  },
  "Residences Apartments/Joni Residence PDF/Kati 1/Joni-K1-130.6m².pdf": {
    "rooms": [
      {
        "name": "Banjo",
        "area": 4,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 10.4,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 12.5,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 9.9,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 14,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 8.9,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 25,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 1.6,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Terasë",
        "area": 30.6,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "3+1"
  },
  "Residences Apartments/Joni Residence PDF/Kati 1/Joni-K1-91.2m².pdf": {
    "rooms": [],
    "type": "2+1"
  },
  "Residences Apartments/Joni Residence PDF/Kati 2-6/Joni-K2-6-106.8m².pdf": {
    "rooms": [
      {
        "name": "Ballkoni",
        "area": 12.6,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Banjo",
        "area": 4,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 10.4,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 12.5,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 9.9,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 14,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 8.9,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 25,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 1.6,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "3+1"
  },
  "Residences Apartments/Joni Residence PDF/Kati 2-6/Joni-K2-6-80.4m².pdf": {
    "rooms": [
      {
        "name": "Ballkoni",
        "area": 4,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "2+1"
  },
  "Residences Apartments/Joni Residence PDF/Kati 2-6/Joni-K2-6-83.5m².pdf": {
    "rooms": [
      {
        "name": "WC",
        "area": 2.2,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "2+1"
  },
  "Residences Apartments/Joni Residence PDF/Kati 2-6/Joni-K2-6-85.3m².pdf": {
    "rooms": [
      {
        "name": "WC",
        "area": 1.7,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Ballkoni",
        "area": 6.1,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "2+1"
  },
  "Residences Apartments/Tara Residence PDF/Tara-115m².pdf": {
    "rooms": [
      {
        "name": "Qëndrimi ditor",
        "area": 17.1,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 13.2,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.8,
        "floor": "Pllakë keramike"
      },
      {
        "name": "WC",
        "area": 2.5,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.1,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 16.3,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 16.2,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 12.3,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 4.4,
        "floor": "Pllakë Keramike"
      }
    ],
    "type": "3+1",
    "totalArea": 115
  },
  "Residences Apartments/Tara Residence PDF/Tara-120.1m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 14,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 6.4,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 6.9,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 21.5,
        "floor": "Parket"
      }
    ],
    "type": "2+1",
    "totalArea": 120.1
  },
  "Residences Apartments/Tara Residence PDF/Tara-122.5m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 11.3,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13,
        "floor": "Parket"
      },
      {
        "name": "WC",
        "area": 3.8,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 20.3,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 12.1,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 27.1,
        "floor": "Pllakë Keramike"
      }
    ],
    "type": "2+1",
    "totalArea": 122.5
  },
  "Residences Apartments/Tara Residence PDF/Tara-129.0m².pdf": {
    "rooms": [
      {
        "name": "Ballkoni",
        "area": 6,
        "floor": "Pllakë Keramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 16.1,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 10.2,
        "floor": "Parket"
      },
      {
        "name": "WC",
        "area": 3.1,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Banjo",
        "area": 4.5,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 19.3,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 11.9,
        "floor": "Parket"
      }
    ],
    "type": "3+1",
    "totalArea": 129
  },
  "Residences Apartments/Tara Residence PDF/Tara-129.4m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 12.4,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.2,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 12.9,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 20.2,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 12.4,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 18,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.9,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Banjo",
        "area": 4,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Ballkoni",
        "area": 9.9,
        "floor": "Pllakë Keramike"
      },
      {
        "name": "Ballkoni",
        "area": 2.1,
        "floor": "Pllakë Keramike"
      }
    ],
    "type": "3+1",
    "totalArea": 129.4
  },
  "Residences Apartments/Tara Residence PDF/Tara-139.5m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 14,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 6.4,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 11.4,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 18.7,
        "floor": "Parket"
      }
    ],
    "type": "2+1",
    "totalArea": 139.5
  },
  "Residences Apartments/Tara Residence PDF/Tara-145.1m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 11.2,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.9,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 17.6,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.5,
        "floor": "Pllakë keramike"
      },
      {
        "name": "WC",
        "area": 2.5,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 20.7,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 17.1,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 8.1,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 25.5,
        "floor": "Pllakë Keramike"
      }
    ],
    "type": "2+1",
    "totalArea": 145.1
  },
  "Residences Apartments/Tara Residence PDF/Tara-159.1m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 10.7,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.5,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.8,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 9.9,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.3,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 4.3,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 15.7,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 22.9,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 17.5,
        "floor": "Parket"
      },
      {
        "name": "WC",
        "area": 1.9,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "4+1",
    "totalArea": 159.1
  },
  "Residences Apartments/Tara Residence PDF/Tara-183.3m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 12.6,
        "floor": "Parket"
      },
      {
        "name": "WC",
        "area": 3.2,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Depo",
        "area": 3.9,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 5,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 17,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 14.6,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 9.9,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 26,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 17,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 35.7,
        "floor": "Pllakë Keramike"
      }
    ],
    "type": "2+1",
    "totalArea": 183.3
  },
  "Residences Apartments/Tara Residence PDF/Tara-46.1m².pdf": {
    "rooms": [
      {
        "name": "Qëndrimi ditor",
        "area": 10.6,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 9.9,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 3.4,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 4.7,
        "floor": "Pllakë Keramike"
      }
    ],
    "type": "1+1",
    "totalArea": 46.1
  },
  "Residences Apartments/Tara Residence PDF/Tara-64.3m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 9.9,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 9.4,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 11.2,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 10.4,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Ballkoni",
        "area": 5.6,
        "floor": "Pllakë Keramike"
      }
    ],
    "type": "2+1",
    "totalArea": 64.3
  },
  "Residences Apartments/Tara Residence PDF/Tara-74.13m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 9.6,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 6.2,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 13.6,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.5,
        "floor": "Pllakë keramike"
      },
      {
        "name": "WC",
        "area": 2.1,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Ballkoni",
        "area": 6.1,
        "floor": "Pllakë Keramike"
      }
    ],
    "type": "2+1",
    "totalArea": 74.13
  },
  "Residences Apartments/Tara Residence PDF/Tara-74.3m².pdf": {
    "rooms": [
      {
        "name": "Banjo",
        "area": 4.5,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 9.5,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 10.8,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 13.1,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 5.7,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 6,
        "floor": "Pllakë Keramike"
      },
      {
        "name": "WC",
        "area": 1.9,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "2+1",
    "totalArea": 74.3
  },
  "Residences Apartments/Tara Residence PDF/Tara-76.7m².pdf": {
    "rooms": [
      {
        "name": "Kuzhina/Tryezaria",
        "area": 11.5,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 9.6,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 7.4,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 12.5,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 5.3,
        "floor": "Pllakë keramike"
      },
      {
        "name": "WC",
        "area": 2.7,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 12.5,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 4,
        "floor": "Pllakë Keramike"
      }
    ],
    "type": "2+1",
    "totalArea": 76.7
  },
  "Residences Apartments/Tara Residence PDF/Tara-91.2m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 11.9,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.8,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 13.5,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 16.3,
        "floor": "Parket"
      },
      {
        "name": "WC",
        "area": 2.5,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Banjo",
        "area": 4.8,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Depo",
        "area": 2.4,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 10.5,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 5.2,
        "floor": "Pllakë Keramike"
      }
    ],
    "type": "2+1",
    "totalArea": 91.2
  },
  "Residences Apartments/Tara Residence PDF/Tara-93.8m².pdf": {
    "rooms": [
      {
        "name": "Banjo",
        "area": 4.5,
        "floor": "Pllakë keramike"
      },
      {
        "name": "WC",
        "area": 2.4,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.5,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 10.4,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 20,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 11.2,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 9.1,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 2.2,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 5.9,
        "floor": "Pllakë Keramike"
      }
    ],
    "type": "2+1",
    "totalArea": 93.8
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku A/Tiani-A-107.4m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 13.9,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 14.4,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 1.7,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 18.2,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 11.9,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.8,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Terasë",
        "area": 19.7,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 7.7,
        "floor": "Parket"
      },
      {
        "name": "WC",
        "area": 2.3,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "2+1",
    "totalArea": 107.4
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku A/Tiani-A-115.5m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 9.8,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 16.5,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 12.7,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 15.5,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 5.4,
        "floor": "Pllakë keramike"
      },
      {
        "name": "WC",
        "area": 2.3,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Banjo",
        "area": 4.5,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.8,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 17,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 2.3,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "3+1",
    "totalArea": 115.5
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku A/Tiani-A-116.6m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 12.9,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 2.6,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 12.4,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 13.9,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.3,
        "floor": "Pllakë keramike"
      },
      {
        "name": "WC",
        "area": 2.6,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 22,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 5.6,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "3+1",
    "totalArea": 116.6
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku A/Tiani-A-130.7m².pdf": {
    "rooms": [
      {
        "name": "Banjo",
        "area": 3.6,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Terasë",
        "area": 10.6,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 18,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 15.3,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.5,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 3.9,
        "floor": "Pllakë keramike"
      },
      {
        "name": "WC",
        "area": 3.5,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Depo",
        "area": 3,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 18.8,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 10.9,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 12.1,
        "floor": "Parket"
      }
    ],
    "type": "3+1",
    "totalArea": 130.7
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku A/Tiani-A-130.9m².pdf": {
    "rooms": [
      {
        "name": "Terasë",
        "area": 11.9,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 12.3,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 2,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 19.6,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 17.5,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 11.9,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 15.1,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 5.2,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Banjo",
        "area": 3.6,
        "floor": "Pllakë keramike"
      },
      {
        "name": "WC",
        "area": 2.1,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "3+1",
    "totalArea": 130.9
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku A/Tiani-A-138.8m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 12.9,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 2.6,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 12.4,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 13.9,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.3,
        "floor": "Pllakë keramike"
      },
      {
        "name": "WC",
        "area": 2.6,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Terasë",
        "area": 27.8,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 22,
        "floor": "Parket"
      }
    ],
    "type": "3+1",
    "totalArea": 138.8
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku A/Tiani-A-184.8m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 20.2,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 14.8,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 15.3,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 19.9,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 6.6,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Depo",
        "area": 3.1,
        "floor": "Pllakë keramike"
      },
      {
        "name": "WC",
        "area": 2.7,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Banjo",
        "area": 5.7,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Banjo",
        "area": 4,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 13,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 19.9,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 19.6,
        "floor": "Parket"
      },
      {
        "name": "Terasë",
        "area": 11,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Banjo",
        "area": 4.9,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "4+1",
    "totalArea": 184.8
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku A/Tiani-A-90.2m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 9.8,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 17,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 2.3,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 10.8,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 3.8,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 16.2,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 12.7,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 5.4,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "2+1",
    "totalArea": 90.2
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku A/Tiani-A-92.1m².pdf": {
    "rooms": [
      {
        "name": "Banjo",
        "area": 4.3,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 13.1,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 10.4,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 14.6,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 12.6,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 1.7,
        "floor": "Pllakë keramike"
      },
      {
        "name": "WC",
        "area": 2.1,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 14.5,
        "floor": "Parket"
      },
      {
        "name": "Ballkoni",
        "area": 5.3,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "2+1",
    "totalArea": 92.1
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku A/Tiani-A-93.5m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 14.3,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 13.5,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 1.7,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 18.2,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 11.9,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.7,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 7.5,
        "floor": "Parket"
      },
      {
        "name": "WC",
        "area": 2.3,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Ballkoni",
        "area": 6.7,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "2+1",
    "totalArea": 93.5
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku A/Tiani-A-94.4m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 13.9,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 14.4,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 1.7,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 18.2,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 11.9,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 4.8,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 7.7,
        "floor": "Parket"
      },
      {
        "name": "WC",
        "area": 2.3,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Ballkoni",
        "area": 6.7,
        "floor": "Pllakë keramike"
      }
    ],
    "type": "2+1",
    "totalArea": 94.4
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku A/Tiani-A-99.0m².pdf": {
    "rooms": [
      {
        "name": "Terasë",
        "area": 12.2,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Banjo",
        "area": 4.3,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 13.1,
        "floor": "Parket"
      },
      {
        "name": "Koridori",
        "area": 10.4,
        "floor": "Parket"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 14.6,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 12.6,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 1.7,
        "floor": "Pllakë keramike"
      },
      {
        "name": "WC",
        "area": 2.1,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Dhomë gjumi",
        "area": 14.5,
        "floor": "Parket"
      }
    ],
    "type": "2+1",
    "totalArea": 99
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku A/Tiani-A-99.1m².pdf": {
    "rooms": [
      {
        "name": "Dhomë gjumi",
        "area": 9.8,
        "floor": "Parket"
      },
      {
        "name": "Dhomë gjumi",
        "area": 17,
        "floor": "Parket"
      },
      {
        "name": "Depo",
        "area": 2.3,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Koridori",
        "area": 10.8,
        "floor": "Parket"
      },
      {
        "name": "Banjo",
        "area": 3.8,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Terasë",
        "area": 13.4,
        "floor": "Pllakë keramike"
      },
      {
        "name": "Qëndrimi ditor",
        "area": 16.2,
        "floor": "Parket"
      },
      {
        "name": "Kuzhina/Tryezaria",
        "area": 12.7,
        "floor": "Parket"
      }
    ],
    "type": "2+1",
    "totalArea": 99.1
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku B/Tiani-B-144.7m².pdf": {
    "rooms": [],
    "type": "3+1",
    "totalArea": 144.7
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku B/Tiani-B-150.5m².pdf": {
    "rooms": [],
    "type": "3+1",
    "totalArea": 150.5
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku B/Tiani-B-179.1m².pdf": {
    "rooms": [],
    "type": "3+1",
    "totalArea": 179.1
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku B/Tiani-B-68.6m².pdf": {
    "rooms": [],
    "type": "1+1",
    "totalArea": 68.6
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku B/Tiani-B-84.9m².pdf": {
    "rooms": [],
    "type": "2+1",
    "totalArea": 84.9
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku B/Tiani-B-87.8m².pdf": {
    "rooms": [],
    "type": "2+1",
    "totalArea": 87.8
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku B/Tiani-B-88.0m².pdf": {
    "rooms": [],
    "type": "2+1",
    "totalArea": 88
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku B/Tiani-B-88.7m².pdf": {
    "rooms": [],
    "type": "2+1",
    "totalArea": 88.7
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku B/Tiani-B-88.8m².pdf": {
    "rooms": [],
    "type": "2+1",
    "totalArea": 88.8
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku B/Tiani-B-90.0m².pdf": {
    "rooms": [],
    "type": "2+1",
    "totalArea": 90
  },
  "Residences Apartments/Tiani Residence PDF/Tiani Blloku B/Tiani-B-92.6m².pdf": {
    "rooms": [],
    "type": "2+1",
    "totalArea": 92.6
  }
}
